import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import DashboardView from '@/components/View/DashboardView'
import { isUserAuthenticated } from '@/components/Utils/Auth/userAuth'
import AuthWrapper from '@/components/Utils/Auth/authWrapper'



const Home = () => {
  return (
    <>
      <Head>
        <title>Moufit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {!isUserAuthenticated && ( */}
        <DashboardView />
      {/* )} */}

    </>
  )
};

// export default AuthWrapper(Home);
export default Home;

